/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Estacion_Expres;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI-THIN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblLog = new javax.swing.JLabel();
        lblTexIni = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblCon = new javax.swing.JLabel();
        btnIni = new javax.swing.JButton();
        chbxMostrar = new javax.swing.JCheckBox();
        lblMoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\bloqueo-de-nube.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 80, 90));

        lblLog.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\OneDrive\\Imágenes\\Capturas de pantalla\\Captura de pantalla 2023-08-08 100959.png")); // NOI18N
        jPanel1.add(lblLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 470, 540));

        lblTexIni.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        lblTexIni.setForeground(new java.awt.Color(87, 87, 87));
        lblTexIni.setText("ESTACION EXPRES");
        jPanel1.add(lblTexIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 150, -1));

        lblCon.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        lblCon.setForeground(new java.awt.Color(87, 87, 87));
        lblCon.setText("CLAVE DE ACCESO:");
        jPanel1.add(lblCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 130, 20));

        btnIni.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        btnIni.setForeground(new java.awt.Color(87, 87, 87));
        btnIni.setText("INGRESAR");
        btnIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniActionPerformed(evt);
            }
        });
        jPanel1.add(btnIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        chbxMostrar.setSelected(true);
        chbxMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(chbxMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        lblMoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\scooter_motorbike_motorcycle_icon_227541 (1).png")); // NOI18N
        jPanel1.add(lblMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 80, 70));

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniActionPerformed
        // TODO add your handling code here:
//         String user = txtUsu.getText();
        String pass = String.valueOf(txtPass.getPassword());
        String consulta = "call sistema_parqueadero.Validacion_Credenciales('" + pass + "')";
        System.out.println(consulta);
        Conec cn = new Conec();

        try {
            ResultSet res = cn.EjecutaSQL(consulta);
            if (res.next()) {
                System.out.println(res);
                if (pass.isBlank()) {
                    JOptionPane.showMessageDialog(null, "Tiene campos en blanco", "Error", JOptionPane.ERROR_MESSAGE);
                } else if (res.getInt(1) == 1) {
                    Menu ad = new Menu();
                    ad.setVisible(true);
                    this.setVisible(false);
                    LocalDateTime horaIngreso = LocalDateTime.now();
                    System.out.println("Hora de ingreso: " + horaIngreso);

//                    String registro = "Usuario: " + user + ", Hora de ingreso: " + horaIngreso;
//                    guardarRegistro(registro);
                } else if (res.getInt(1) == 2) {
                    System.out.println("hola");
                } else if (res.getInt(1) == 0) {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_btnIniActionPerformed

    private void chbxMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxMostrarActionPerformed
        if(chbxMostrar.isSelected()){
            txtPass.setEchoChar('*');
        } else {
            txtPass.setEchoChar((char)0);
        }
    }//GEN-LAST:event_chbxMostrarActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIni;
    private javax.swing.JCheckBox chbxMostrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCon;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblMoto;
    private javax.swing.JLabel lblTexIni;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
