/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Estacion_Expres;

import com.mycompany.proyecto_final.Disponibilidad;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-THIN
 */
public class Vehiculo extends javax.swing.JFrame {

    /**
     * Creates new form Vehiculo
     */
    private void limpiar() {
        txtMatr.setText(null);
        txtCedCli.setText(null);
        ComboxTipo.setSelectedItem(null);
        CmboxMarca.setSelectedItem(null);
        ComboxModelo.setSelectedItem(null);
        ComboxColor.setSelectedItem(null);
    }

    public void Comb_Tipo() {
        String sql = "call sistema_parqueadero.OBTENERCATPADRE(1)";
        Conec c1 = new Conec();
        try {
            ResultSet res = c1.EjecutaSQL(sql);
            while (res.next()) {
                ComboxTipo.addItem(res.getString("Cat_Nombre"));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Comb_Color() {
        String sql = "call sistema_parqueadero.OBTENERCATPADRE(4)";
        Conec c1 = new Conec();
        try {
            ResultSet res = c1.EjecutaSQL(sql);
            while (res.next()) {
                ComboxColor.addItem(res.getString("Cat_Nombre"));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Vehiculo() {
        initComponents();
        mostrarTablaVe();
        Comb_Tipo();
        Comb_Color();
        Cliente c = new Cliente();
        txtCedCli.setText(c.cedulaa);
        setLocationRelativeTo(null);
        this.dispose();
        
//       txtCedCli.setText(Integer.toString(cedulaa));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlV = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblaVe = new javax.swing.JTable();
        txtMatr = new javax.swing.JTextField();
        txtCedCli = new javax.swing.JTextField();
        btnRegistr = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ComboxTipo = new javax.swing.JComboBox<>();
        ComboxColor = new javax.swing.JComboBox<>();
        ComboxModelo = new javax.swing.JComboBox<>();
        CmboxMarca = new javax.swing.JComboBox<>();
        btnBus = new javax.swing.JButton();
        btn_Atra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnSegu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlV.setBackground(new java.awt.Color(153, 204, 255));

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(87, 87, 87));
        jLabel8.setText("VEHICULOS");

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(87, 87, 87));
        jLabel9.setText("MATRICULA: ");

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(87, 87, 87));
        jLabel10.setText("CEDULA CLIENTE: ");

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(87, 87, 87));
        jLabel11.setText("MARCA:");

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(87, 87, 87));
        jLabel12.setText("MODELO:");

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(87, 87, 87));
        jLabel13.setText("COLOR: ");

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(87, 87, 87));
        jLabel14.setText("TIPO:");

        TblaVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MATRICULA", "CEDULA CLIENTE", "MARCA", "MODELO", "COLOR", "TIPO"
            }
        ));
        TblaVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblaVeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblaVe);

        txtMatr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatrActionPerformed(evt);
            }
        });

        txtCedCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedCliActionPerformed(evt);
            }
        });

        btnRegistr.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        btnRegistr.setForeground(new java.awt.Color(87, 87, 87));
        btnRegistr.setText("REGISTRAR");
        btnRegistr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(87, 87, 87));
        jButton4.setText("ELIMINAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ComboxTipo.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        ComboxTipo.setForeground(new java.awt.Color(87, 87, 87));
        ComboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de vehiculo" }));
        ComboxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxTipoActionPerformed(evt);
            }
        });

        ComboxColor.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        ComboxColor.setForeground(new java.awt.Color(87, 87, 87));
        ComboxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un color" }));
        ComboxColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxColorActionPerformed(evt);
            }
        });

        ComboxModelo.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        ComboxModelo.setForeground(new java.awt.Color(87, 87, 87));
        ComboxModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el modelo" }));
        ComboxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxModeloActionPerformed(evt);
            }
        });

        CmboxMarca.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        CmboxMarca.setForeground(new java.awt.Color(87, 87, 87));
        CmboxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una marca" }));
        CmboxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmboxMarcaActionPerformed(evt);
            }
        });

        btnBus.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        btnBus.setForeground(new java.awt.Color(87, 87, 87));
        btnBus.setText("BUSCAR");
        btnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusActionPerformed(evt);
            }
        });

        btn_Atra.setForeground(new java.awt.Color(87, 87, 87));
        btn_Atra.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\flecha-izquierda (1).png")); // NOI18N
        btn_Atra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtraActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\parking-6b_thumbnail (1).jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\parking-6b_thumbnail (1).jpg")); // NOI18N
        jLabel2.setText("jLabel1");

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\conduciendo.png")); // NOI18N
        jLabel15.setText("jLabel8");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\carro-nuevo (2).png")); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\carro-nuevo (3).png")); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\line_96368.png")); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\line_96368.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\coche-de-carreras.png")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\coche-de-carreras.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\coche-de-carreras.png")); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\line_96368.png")); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\line_96368.png")); // NOI18N

        btnSegu.setIcon(new javax.swing.ImageIcon("C:\\Users\\MSI-THIN\\Downloads\\proximo (1).png")); // NOI18N
        btnSegu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVLayout = new javax.swing.GroupLayout(pnlV);
        pnlV.setLayout(pnlVLayout);
        pnlVLayout.setHorizontalGroup(
            pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVLayout.createSequentialGroup()
                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addComponent(btn_Atra)
                                .addGap(297, 297, 297))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179)))
                        .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlVLayout.createSequentialGroup()
                                        .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CmboxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addGroup(pnlVLayout.createSequentialGroup()
                                                .addComponent(txtCedCli, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBus)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addGap(0, 8, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(332, 332, 332)
                                .addComponent(btnSegu)
                                .addGap(30, 30, 30))))
                    .addGroup(pnlVLayout.createSequentialGroup()
                        .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVLayout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVLayout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(105, 105, 105)))))
                        .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(215, 215, 215))
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMatr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegistr, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVLayout.createSequentialGroup()
                                        .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(56, 56, 56))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVLayout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)))))))
                .addContainerGap())
        );
        pnlVLayout.setVerticalGroup(
            pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVLayout.createSequentialGroup()
                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Atra)
                            .addComponent(btnSegu)))
                    .addGroup(pnlVLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)))
                .addGap(28, 28, 28)
                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlVLayout.createSequentialGroup()
                        .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMatr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCedCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CmboxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)))
                        .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRegistr)
                                    .addComponent(jButton4))
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlVLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel15)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))))
                    .addGroup(pnlVLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(pnlV, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 960, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TblaVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblaVeMouseClicked
        // TODO add your handling code here:
        txtMatr.setText(TblaVe.getValueAt(TblaVe.getSelectedRow(), 0).toString());
        txtCedCli.setText(TblaVe.getValueAt(TblaVe.getSelectedRow(), 1).toString());
        ComboxTipo.setSelectedItem(TblaVe.getValueAt(TblaVe.getSelectedRow(), 5).toString());
        CmboxMarca.setSelectedItem(TblaVe.getValueAt(TblaVe.getSelectedRow(), 2).toString());
        ComboxModelo.setSelectedItem(TblaVe.getValueAt(TblaVe.getSelectedRow(), 3).toString());
        ComboxColor.setSelectedItem(TblaVe.getValueAt(TblaVe.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_TblaVeMouseClicked

    private void txtMatrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatrActionPerformed

    private void txtCedCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedCliActionPerformed
        // TODO add your handling code here: 

    }//GEN-LAST:event_txtCedCliActionPerformed

    private void btnRegistrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrActionPerformed
        // TODO add your handling code here:
        Conec c1 = new Conec();

        String matricula = txtMatr.getText();
        int cedulacli = Integer.parseInt(txtCedCli.getText());
        String marca = CmboxMarca.getSelectedItem().toString();
        String modelo = ComboxModelo.getSelectedItem().toString();
        String color = ComboxColor.getSelectedItem().toString();
        String tipo = ComboxTipo.getSelectedItem().toString();
        String sql1 = "call sistema_parqueadero.BUSCARVEHI('" + matricula + "');";


        try {
            ResultSet re = c1.EjecutaSQL(sql1);
            if (re.next()) {
                int selectedRow = TblaVe.getSelectedRow();
                String sql2 = ("call sistema_parqueadero.ModificarVehi('" + matricula + "','" + cedulacli + "','" + marca + "','" + modelo + "','" + color + "','" + tipo + "')");
                
                c1.EjecutaSQL(sql2);
            } else {
                String sql3 = ("call sistema_parqueadero.INSERTARVE('" + matricula + "','" + cedulacli + "','" + marca + "','" + modelo + "','" + color + "','" + tipo + "')");
                c1.EjecutaSQLIUD(sql3);
            }
        } catch (ClassNotFoundException e) {
        } catch (SQLException ex) {
            Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        mostrarTablaVe();
        limpiar();
        Disponibilidad d = new Disponibilidad();
        d.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRegistrActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = TblaVe.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String Veh_Matricula = TblaVe.getValueAt(selectedRow, 0).toString();

        try {
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sistema_parqueadero?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "2002");

            // Llamar al procedimiento almacenado para eliminar el registro
            String sql = "call sistema_parqueadero.ELIMINARVE(?)";
            CallableStatement statement = connection.prepareCall(sql);
            statement.setString(1, Veh_Matricula);
            statement.execute();

            statement.close();
            connection.close();
            // Eliminar la fila de la tabla
            DefaultTableModel model = (DefaultTableModel) TblaVe.getModel();
            model.removeRow(selectedRow);

            JOptionPane.showMessageDialog(this, "Cliente eliminado correctamente.", "Eliminación Exitosa", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar .", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
//        mostrarTablaVe();
//        limpiar();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void ComboxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxTipoActionPerformed
        // TODO add your handling code here:
        String sql2 = "call sistema_parqueadero.BUSCARCATEGO('" + ComboxTipo.getSelectedItem() + "')";
        Conec c1 = new Conec();
        try {
            ResultSet res = c1.EjecutaSQL(sql2);
            while (res.next()) {
                String sql1 = "call sistema_parqueadero.OBTENERCATPADRE(" + res.getInt("Cat_Id") + ")";
                res = c1.EjecutaSQL(sql1);
                CmboxMarca.removeAllItems();
                while (res.next()) {
                    CmboxMarca.addItem(res.getString("Cat_Nombre"));
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboxTipoActionPerformed

    private void ComboxColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboxColorActionPerformed

    private void ComboxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxModeloActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_ComboxModeloActionPerformed

    private void CmboxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmboxMarcaActionPerformed
        // TODO add your handling code here:
        String sql2 = "call sistema_parqueadero.BUSCARCATEGO('" + CmboxMarca.getSelectedItem() + "')";
        Conec c1 = new Conec();
        try {
            ResultSet res = c1.EjecutaSQL(sql2);
            while (res.next()) {
                String sql1 = "call sistema_parqueadero.OBTENERCATPADRE(" + res.getInt("Cat_Id") + ")";
                res = c1.EjecutaSQL(sql1);
                ComboxModelo.removeAllItems();
                while (res.next()) {
                    ComboxModelo.addItem(res.getString("Cat_Nombre"));
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CmboxMarcaActionPerformed

    private void btnBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusActionPerformed
        // TODO add your handling code here:
        Conec c = new Conec();
    String cedula = txtCedCli.getText();

    if (cedula.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de cédula.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "CALL sistema_parqueadero.ObtenerDetallesVehiculo('" + cedula + "');";

    try {
        ResultSet res = c.EjecutaSQL(sql);
        if (res.next()) {
            JOptionPane.showMessageDialog(this, "Cliente existente.", "Cliente", JOptionPane.INFORMATION_MESSAGE);
            txtCedCli.setText(res.getString("Per_Cedula"));
            txtMatr.setText(res.getString("Veh_Matricula"));
            ComboxTipo.setSelectedItem(res.getString("Veh_Tipo"));
            CmboxMarca.setSelectedItem(res.getString("Veh_Marca"));
            ComboxModelo.setSelectedItem(res.getString("Veh_Modelo"));
            ComboxColor.setSelectedItem(res.getString("Veh_Color"));
        } else {
            int opcion = JOptionPane.showConfirmDialog(null, "Cliente no existe,Desea registrar un nuevo cliente?", "Registrar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                Cliente cl = new Cliente();
                cl.setVisible(true);
            } else if (opcion == JOptionPane.NO_OPTION) {
                System.out.println("El usuario eligió 'No'");
            }
        }
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Vehiculo.class.getName()).log(Level.SEVERE, null, ex);
    }
    mostrarTablaVe();

    }//GEN-LAST:event_btnBusActionPerformed

    private void btn_AtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtraActionPerformed
        // TODO add your handling code here:
        Cliente cl = new Cliente();
        cl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_AtraActionPerformed

    private void btnSeguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguActionPerformed
        // TODO add your handling code here:
        Disponibilidad d = new Disponibilidad();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSeguActionPerformed

    public void mostrarTablaVe() {
        String sql;
        if (txtCedCli.getText().isEmpty()) {
            sql = ("call sistema_parqueadero.MOSTRARVE();");
        } else {
            sql = "call sistema_parqueadero.ObtenerDetallesVehiculo('" + txtCedCli.getText() + "');";
        }

        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelo.addColumn("MATRICULA");
        modelo.addColumn("CEDULA CLIENTE");
        modelo.addColumn("MARCA");
        modelo.addColumn("MODELO");
        modelo.addColumn("COLOR");
        modelo.addColumn("TIPO");

        TblaVe.setModel(modelo);
        String[] datos = new String[6];
        try {
            Conec c1 = new Conec();
            ResultSet res = c1.EjecutaSQL(sql);
            while (res.next()) {
                datos[0] = res.getString(1);
                datos[1] = res.getString(2);
                datos[2] = res.getString(3);
                datos[3] = res.getString(4);
                datos[4] = res.getString(5);
                datos[5] = res.getString(6);
                modelo.addRow(datos);

            }
            res.close();
            TblaVe.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showInternalMessageDialog(null, "error" + e.toString());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmboxMarca;
    private javax.swing.JComboBox<String> ComboxColor;
    private javax.swing.JComboBox<String> ComboxModelo;
    private javax.swing.JComboBox<String> ComboxTipo;
    private javax.swing.JTable TblaVe;
    private javax.swing.JButton btnBus;
    private javax.swing.JButton btnRegistr;
    private javax.swing.JButton btnSegu;
    private javax.swing.JButton btn_Atra;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlV;
    private javax.swing.JTextField txtCedCli;
    private javax.swing.JTextField txtMatr;
    // End of variables declaration//GEN-END:variables
}
